/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
import javax.swing.JFrame;

public class axismfpc extends javax.swing.JFrame {

    /**
     * Creates new form axismfpc
     */
    public axismfpc() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hlin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lreturns1 = new javax.swing.JLabel();
        lreturns2 = new javax.swing.JLabel();
        lreturns3 = new javax.swing.JLabel();
        lreturns4 = new javax.swing.JLabel();
        lreturns5 = new javax.swing.JLabel();
        lreturns6 = new javax.swing.JLabel();
        lreturns7 = new javax.swing.JLabel();
        pcclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(118, 255, 3));

        hlin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        hlin.setForeground(new java.awt.Color(46, 49, 50));
        hlin.setText("Smart Finance Planner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(hlin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hlin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 60);

        jPanel1.setBackground(new java.awt.Color(46, 49, 50));

        lreturns1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lreturns1.setForeground(new java.awt.Color(232, 236, 246));
        lreturns1.setText("Pros:");

        lreturns2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lreturns2.setForeground(new java.awt.Color(189, 195, 199));
        lreturns2.setText("1) Lower expense ratio - 0.44%");

        lreturns3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lreturns3.setForeground(new java.awt.Color(189, 195, 199));
        lreturns3.setText("2) 1Y Returns are higher than the category average returns (Avg: -16.9%)");

        lreturns4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lreturns4.setForeground(new java.awt.Color(189, 195, 199));
        lreturns4.setText("4) 5Y Returns are higher than the category average returns (Avg: 7.0%)");
        lreturns4.setToolTipText("");

        lreturns5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lreturns5.setForeground(new java.awt.Color(189, 195, 199));
        lreturns5.setText("3) 3Y Returns are higher than the category average returns (Avg: 0.9%)");

        lreturns6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lreturns6.setForeground(new java.awt.Color(232, 236, 246));
        lreturns6.setText("Cons:");

        lreturns7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lreturns7.setForeground(new java.awt.Color(189, 195, 199));
        lreturns7.setText("1) Risk-adjusted returns are lower compared to the category");

        pcclose.setBackground(new java.awt.Color(242, 38, 19));
        pcclose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pcclose.setText("CLOSE");
        pcclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pccloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lreturns7)
                            .addComponent(lreturns6)
                            .addComponent(lreturns5)
                            .addComponent(lreturns4)
                            .addComponent(lreturns3)
                            .addComponent(lreturns2)
                            .addComponent(lreturns1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(pcclose, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lreturns1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lreturns2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lreturns3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lreturns5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lreturns4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lreturns6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lreturns7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(pcclose, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 720, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pccloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pccloseActionPerformed
        dispose();
    }//GEN-LAST:event_pccloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(axismfpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(axismfpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(axismfpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(axismfpc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new axismfpc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hlin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lreturns1;
    private javax.swing.JLabel lreturns2;
    private javax.swing.JLabel lreturns3;
    private javax.swing.JLabel lreturns4;
    private javax.swing.JLabel lreturns5;
    private javax.swing.JLabel lreturns6;
    private javax.swing.JLabel lreturns7;
    private javax.swing.JButton pcclose;
    // End of variables declaration//GEN-END:variables
}
