
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class nw extends javax.swing.JFrame {

    /**
     * Creates new form nw
     */
    public nw() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hlin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        f1 = new javax.swing.JPanel();
        tf1 = new javax.swing.JLabel();
        tf1s = new javax.swing.JLabel();
        f2 = new javax.swing.JPanel();
        tf2 = new javax.swing.JLabel();
        tf2s = new javax.swing.JLabel();
        f3 = new javax.swing.JPanel();
        tf3 = new javax.swing.JLabel();
        tf3s = new javax.swing.JLabel();
        f4 = new javax.swing.JPanel();
        tf4 = new javax.swing.JLabel();
        tf4s = new javax.swing.JLabel();
        f5 = new javax.swing.JPanel();
        tf5 = new javax.swing.JLabel();
        tf5s = new javax.swing.JLabel();
        clrb = new javax.swing.JButton();
        ap1 = new javax.swing.JButton();
        ap2 = new javax.swing.JButton();
        ap3 = new javax.swing.JButton();
        ap4 = new javax.swing.JButton();
        ap5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        otherperc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        debtperc = new javax.swing.JLabel();
        eqperc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lcp = new javax.swing.JLabel();
        lmcp = new javax.swing.JLabel();
        mcp = new javax.swing.JLabel();
        scp = new javax.swing.JLabel();
        mulcp = new javax.swing.JLabel();
        comp = new javax.swing.JLabel();
        fofp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fetfp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(118, 255, 3));

        hlin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        hlin.setForeground(new java.awt.Color(46, 49, 50));
        hlin.setText("Smart Finance Planner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(hlin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1240, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hlin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1630, 60);

        jPanel1.setBackground(new java.awt.Color(46, 49, 50));

        f1.setBackground(new java.awt.Color(218, 224, 226));
        f1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        f1.setPreferredSize(new java.awt.Dimension(488, 76));
        f1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f1MouseExited(evt);
            }
        });

        tf1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf1.setForeground(new java.awt.Color(44, 51, 53));

        tf1s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf1s.setForeground(new java.awt.Color(119, 126, 139));

        javax.swing.GroupLayout f1Layout = new javax.swing.GroupLayout(f1);
        f1.setLayout(f1Layout);
        f1Layout.setHorizontalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(f1Layout.createSequentialGroup()
                        .addComponent(tf1s)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        f1Layout.setVerticalGroup(
            f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(tf1s)
                .addContainerGap())
        );

        f2.setBackground(new java.awt.Color(218, 224, 226));
        f2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        f2.setPreferredSize(new java.awt.Dimension(488, 76));
        f2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f2MouseExited(evt);
            }
        });

        tf2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf2.setForeground(new java.awt.Color(44, 51, 53));

        tf2s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf2s.setForeground(new java.awt.Color(119, 126, 139));

        javax.swing.GroupLayout f2Layout = new javax.swing.GroupLayout(f2);
        f2.setLayout(f2Layout);
        f2Layout.setHorizontalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(f2Layout.createSequentialGroup()
                        .addComponent(tf2s)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        f2Layout.setVerticalGroup(
            f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(tf2s)
                .addContainerGap())
        );

        f3.setBackground(new java.awt.Color(218, 224, 226));
        f3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        f3.setPreferredSize(new java.awt.Dimension(488, 76));
        f3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f3MouseExited(evt);
            }
        });

        tf3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf3.setForeground(new java.awt.Color(44, 51, 53));

        tf3s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf3s.setForeground(new java.awt.Color(119, 126, 139));

        javax.swing.GroupLayout f3Layout = new javax.swing.GroupLayout(f3);
        f3.setLayout(f3Layout);
        f3Layout.setHorizontalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(f3Layout.createSequentialGroup()
                        .addComponent(tf3s)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        f3Layout.setVerticalGroup(
            f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(tf3s)
                .addContainerGap())
        );

        f4.setBackground(new java.awt.Color(218, 224, 226));
        f4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        f4.setPreferredSize(new java.awt.Dimension(488, 76));
        f4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f4MouseExited(evt);
            }
        });

        tf4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf4.setForeground(new java.awt.Color(44, 51, 53));

        tf4s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf4s.setForeground(new java.awt.Color(119, 126, 139));

        javax.swing.GroupLayout f4Layout = new javax.swing.GroupLayout(f4);
        f4.setLayout(f4Layout);
        f4Layout.setHorizontalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf4, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(f4Layout.createSequentialGroup()
                        .addComponent(tf4s)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        f4Layout.setVerticalGroup(
            f4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(tf4s)
                .addContainerGap())
        );

        f5.setBackground(new java.awt.Color(218, 224, 226));
        f5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        f5.setPreferredSize(new java.awt.Dimension(488, 76));
        f5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                f5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                f5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                f5MouseExited(evt);
            }
        });

        tf5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tf5.setForeground(new java.awt.Color(44, 51, 53));

        tf5s.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf5s.setForeground(new java.awt.Color(119, 126, 139));

        javax.swing.GroupLayout f5Layout = new javax.swing.GroupLayout(f5);
        f5.setLayout(f5Layout);
        f5Layout.setHorizontalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf5, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(f5Layout.createSequentialGroup()
                        .addComponent(tf5s)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        f5Layout.setVerticalGroup(
            f5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(f5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(tf5s)
                .addContainerGap())
        );

        clrb.setBackground(new java.awt.Color(242, 38, 19));
        clrb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clrb.setText("close");
        clrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbActionPerformed(evt);
            }
        });

        ap1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ap1.setText("Add to Portfolio");
        ap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ap1MouseClicked(evt);
            }
        });
        ap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap1ActionPerformed(evt);
            }
        });

        ap2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ap2.setText("Add to Portfolio");
        ap2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ap2MouseClicked(evt);
            }
        });
        ap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap2ActionPerformed(evt);
            }
        });

        ap3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ap3.setText("Add to Portfolio");
        ap3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ap3MouseClicked(evt);
            }
        });
        ap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap3ActionPerformed(evt);
            }
        });

        ap4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ap4.setText("Add to Portfolio");
        ap4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ap4MouseClicked(evt);
            }
        });
        ap4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap4ActionPerformed(evt);
            }
        });

        ap5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ap5.setText("Add to Portfolio");
        ap5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ap5MouseClicked(evt);
            }
        });
        ap5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("MY PORTFOLIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(118, 255, 3));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(118, 255, 3));
        jLabel1.setText("TOP SUGGESTION FOR YOU ACCORDING TO YOUR REQUIREMENTS :");

        jPanel3.setBackground(new java.awt.Color(97, 108, 111));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROPORTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("EQUITY:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(150, 30, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("OTHERS:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(300, 30, 90, 20);

        otherperc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otherperc.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(otherperc);
        otherperc.setBounds(390, 30, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("DEBT:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 30, 60, 20);

        debtperc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        debtperc.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(debtperc);
        debtperc.setBounds(80, 30, 60, 20);

        eqperc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eqperc.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(eqperc);
        eqperc.setBounds(230, 30, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Sectorial                  :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 400, 234, 30);

        secp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        secp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(secp);
        secp.setBounds(310, 400, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Large and Mid Cap  :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 120, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Mid Cap                  :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 160, 230, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Small Cap               :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 200, 222, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Multi Cap                :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 240, 230, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Commodities           :");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 280, 230, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Fund of Funds         :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 320, 230, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Large Cap               :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 80, 230, 30);

        lcp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lcp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(lcp);
        lcp.setBounds(310, 80, 120, 30);

        lmcp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lmcp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(lmcp);
        lmcp.setBounds(310, 120, 120, 30);

        mcp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mcp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(mcp);
        mcp.setBounds(310, 160, 120, 30);

        scp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(scp);
        scp.setBounds(310, 200, 120, 30);

        mulcp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mulcp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(mulcp);
        mulcp.setBounds(310, 240, 120, 30);

        comp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(comp);
        comp.setBounds(310, 280, 120, 30);

        fofp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fofp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(fofp);
        fofp.setBounds(310, 320, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Foreign ETFs           :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 360, 226, 30);

        fetfp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fetfp.setForeground(new java.awt.Color(118, 255, 3));
        jPanel3.add(fetfp);
        fetfp.setBounds(310, 360, 120, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(f4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(f3, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                            .addComponent(f2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                                            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ap5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(613, 613, 613)
                        .addComponent(clrb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(320, 320, 320))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(420, 420, 420))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ap3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ap4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ap5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(clrb, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(308, 308, 308))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 1630, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseEntered
        Color c=new Color(71,83,94);
        f1.setBackground(c);
    }//GEN-LAST:event_f1MouseEntered

    private void f1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseExited
        Color c=new Color(218,224,226);
        f1.setBackground(c);
    }//GEN-LAST:event_f1MouseExited

    private void f2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2MouseEntered
        Color c=new Color(71,83,94);
        f2.setBackground(c);
    }//GEN-LAST:event_f2MouseEntered

    private void f2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2MouseExited
        Color c=new Color(218,224,226);
        f2.setBackground(c);
    }//GEN-LAST:event_f2MouseExited

    private void f3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3MouseEntered
        Color c=new Color(71,83,94);
        f3.setBackground(c);
    }//GEN-LAST:event_f3MouseEntered

    private void f3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3MouseExited
        Color c=new Color(218,224,226);
        f3.setBackground(c);
    }//GEN-LAST:event_f3MouseExited

    private void f4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4MouseEntered
        Color c=new Color(71,83,94);
        f4.setBackground(c);
    }//GEN-LAST:event_f4MouseEntered

    private void f4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4MouseExited
        Color c=new Color(218,224,226);
        f4.setBackground(c);
    }//GEN-LAST:event_f4MouseExited

    private void f5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5MouseEntered
        Color c=new Color(71,83,94);
        f5.setBackground(c);
    }//GEN-LAST:event_f5MouseEntered

    private void f5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5MouseExited
        Color c=new Color(218,224,226);
        f5.setBackground(c);
    }//GEN-LAST:event_f5MouseExited

    private void clrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbActionPerformed
        dispose();
    }//GEN-LAST:event_clrbActionPerformed

    private void ap1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap1MouseClicked
        ap1.setText("Done");
        Color c=new Color(0,255,0);
        ap1.setBackground(c);
    }//GEN-LAST:event_ap1MouseClicked

    private void ap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1ActionPerformed
        if(!ap1.getText().equals("Done"))
        {
           MyPortfolio.AddRowToJTable(new Object[] {tf1.getText()});
        }
    }//GEN-LAST:event_ap1ActionPerformed

    private void ap2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap2MouseClicked
        ap2.setText("Done");
        Color c=new Color(0,255,0);
        ap2.setBackground(c);
    }//GEN-LAST:event_ap2MouseClicked

    private void ap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap2ActionPerformed

    private void ap3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap3MouseClicked
        ap3.setText("Done");
        Color c=new Color(0,255,0);
        ap3.setBackground(c);
    }//GEN-LAST:event_ap3MouseClicked

    private void ap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap3ActionPerformed

    private void ap4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap4MouseClicked
        ap4.setText("Done");
        Color c=new Color(0,255,0);
        ap4.setBackground(c);
    }//GEN-LAST:event_ap4MouseClicked

    private void ap4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap4ActionPerformed

    private void ap5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap5MouseClicked
        ap5.setText("Done");
        Color c=new Color(0,255,0);
        ap5.setBackground(c);
    }//GEN-LAST:event_ap5MouseClicked

    private void ap5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MyPortfolio obj=new MyPortfolio();
        if(ap1.getText().equals("Done"))
        {
            MyPortfolio.AddRowToJTable(new Object[] {tf1.getText()});
        }
        if(ap2.getText().equals("Done"))
        {
            MyPortfolio.AddRowToJTable(new Object[] {tf2.getText()});
        }
        if(ap3.getText().equals("Done"))
        {
            MyPortfolio.AddRowToJTable(new Object[] {tf3.getText()});
        }
        if(ap4.getText().equals("Done"))
        {
            MyPortfolio.AddRowToJTable(new Object[] {tf4.getText()});
        }
        if(ap5.getText().equals("Done"))
        {
            MyPortfolio.AddRowToJTable(new Object[] {tf5.getText()});
        }
        obj.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void f1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f1MouseClicked
        if(Integer.parseInt(Planing.dur.getText())<8)
        {
                if(Planing.rcl.isSelected())
                {
                    if(Integer.parseInt(Planing.jtage.getText())<=45)
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/adityabirlasunlifelowdurationfunddirectplang/MBS919").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/adityabirlasunlifelowdurationfunddirectplang/MBS919").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/hdfcshorttermdebtfunddirectplang/MHD1221").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axissmallcapfunddirectplang/MAA316").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
        else
        {
                if(Planing.rcl.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/nipponindiasmallcapfunddirectplang/MRC935").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/franklinindiafeederfranklinusopportunitiesfunddirectplang/MTE305").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/miraeassetemergingbluechipfunddirectplang/MMA100").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
    }//GEN-LAST:event_f1MouseClicked

    private void f2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f2MouseClicked
        if(Integer.parseInt(Planing.dur.getText())<8)
        {
                if(Planing.rcl.isSelected())
                {
                    if(Integer.parseInt(Planing.jtage.getText())<=45)
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/edelweissbankingandpsudebtfunddirectplanfd/MJP367").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/edelweissbankingandpsudebtfunddirectplanfd/MJP367").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/pgimindiadiversifiedequityfunddirectplang/MPA159").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/canararobecoequitydiversifiedfunddirectplang/MCA202").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
        else
        {
                if(Planing.rcl.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/iciciprudentialbondfunddirectplang/MPI1213").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/pgimindiadiversifiedequityfunddirectplang/MPA159").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/nipponindiapharmafunddirectplang/MRC1005").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
    }//GEN-LAST:event_f2MouseClicked

    private void f3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f3MouseClicked
        if(Integer.parseInt(Planing.dur.getText())<8)
        {
                if(Planing.rcl.isSelected())
                {
                    if(Integer.parseInt(Planing.jtage.getText())<=45)
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axisbluechipfunddirectplang/MAA181").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/dspgovernmentsecuritiesfunddirectplang/MDS622").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axisbluechipfunddirectplang/MAA181").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axisbluechipfunddirectplang/MAA181").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
        else
        {
                if(Planing.rcl.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axisbluechipfunddirectplang/MAA181").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/nipponindiasmallcapfunddirectplang/MRC935").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/tatadigitalindiafunddirectplang/MTA1147").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
    }//GEN-LAST:event_f3MouseClicked

    private void f4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f4MouseClicked
        if(Integer.parseInt(Planing.dur.getText())<8)
        {
                if(Planing.rcl.isSelected())
                {
                    if(Integer.parseInt(Planing.jtage.getText())<=45)
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/kotakgoldfunddirectplang/MKM547").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/hdfcshorttermdebtfunddirectplang/MHD1221").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axismidcapfunddirectplang/MAA194").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axismidcapfunddirectplang/MAA194").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
        else
        {
                if(Planing.rcl.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/pgimindiamidcapopportunitiesfunddirectplang/MPA139").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/axismidcapfunddirectplang/MAA194").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/motilaloswalnasdaq100fundfunddirectplang/MMO048").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
    }//GEN-LAST:event_f4MouseClicked

    private void f5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f5MouseClicked
        if(Integer.parseInt(Planing.dur.getText())<8)
        {
                if(Planing.rcl.isSelected())
                {
                    if(Integer.parseInt(Planing.jtage.getText())<=45)
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/utiequityfunddirectplang/MUT651").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else
                    {
                        try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/sbimagnumultrashortdurationfunddirectplang/MSB546").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/miraeassetemergingbluechipfunddirectplang/MMA100").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/miraeassetemergingbluechipfunddirectplang/MMA100").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
        else
        {
                if(Planing.rcl.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/utiequityfunddirectplang/MUT651").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else if(Planing.rcm.isSelected())
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/miraeassetemergingbluechipfunddirectplang/MMA100").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
                else
                {
                    try {
                            Desktop.getDesktop().browse(new URL("https://www.moneycontrol.com/mutual-funds/nav/nipponindiasmallcapfunddirectplang/MRC935").toURI());
                        } catch (URISyntaxException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(Explore_PG1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }
    }//GEN-LAST:event_f5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ap1;
    private javax.swing.JButton ap2;
    private javax.swing.JButton ap3;
    private javax.swing.JButton ap4;
    private javax.swing.JButton ap5;
    private javax.swing.JButton clrb;
    public javax.swing.JLabel comp;
    public javax.swing.JLabel debtperc;
    public javax.swing.JLabel eqperc;
    private javax.swing.JPanel f1;
    private javax.swing.JPanel f2;
    private javax.swing.JPanel f3;
    private javax.swing.JPanel f4;
    private javax.swing.JPanel f5;
    public javax.swing.JLabel fetfp;
    public javax.swing.JLabel fofp;
    private javax.swing.JLabel hlin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lcp;
    public javax.swing.JLabel lmcp;
    public javax.swing.JLabel mcp;
    public javax.swing.JLabel mulcp;
    public javax.swing.JLabel otherperc;
    public javax.swing.JLabel scp;
    public javax.swing.JLabel secp;
    public javax.swing.JLabel tf1;
    public javax.swing.JLabel tf1s;
    public javax.swing.JLabel tf2;
    public javax.swing.JLabel tf2s;
    public javax.swing.JLabel tf3;
    public javax.swing.JLabel tf3s;
    public javax.swing.JLabel tf4;
    public javax.swing.JLabel tf4s;
    public javax.swing.JLabel tf5;
    public javax.swing.JLabel tf5s;
    // End of variables declaration//GEN-END:variables
}
