
import javax.swing.JFrame;
import java.lang.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class Planing extends javax.swing.JFrame {

    /**
     * Creates new form Planing
     */
    public Planing() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        hlin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rcl = new javax.swing.JRadioButton();
        rcm = new javax.swing.JRadioButton();
        rch = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jtreqc = new javax.swing.JTextField();
        jtage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sipm = new javax.swing.JRadioButton();
        ls = new javax.swing.JRadioButton();
        piamt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cgpi = new javax.swing.JLabel();
        dur = new javax.swing.JTextField();
        res1 = new javax.swing.JLabel();
        res2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(118, 255, 3));

        hlin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        hlin.setForeground(new java.awt.Color(46, 49, 50));
        hlin.setText("Smart Finance Planner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(hlin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1210, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hlin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-30, 0, 1600, 62);

        jPanel1.setBackground(new java.awt.Color(46, 49, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 236, 246));
        jLabel1.setText("Duration (in years):");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 236, 246));
        jLabel2.setText("Risk Capability:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 236, 246));
        jLabel3.setText("Required Corpus:");

        rcl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rcl.setForeground(new java.awt.Color(255, 255, 255));
        rcl.setText("Low");
        rcl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rclActionPerformed(evt);
            }
        });

        rcm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rcm.setForeground(new java.awt.Color(255, 255, 255));
        rcm.setText("Medium");
        rcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcmActionPerformed(evt);
            }
        });

        rch.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rch.setForeground(new java.awt.Color(255, 255, 255));
        rch.setText("High");
        rch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 236, 246));
        jLabel4.setText("Age:");

        jtreqc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(118, 255, 3));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Generate Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(242, 38, 19));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 236, 246));
        jLabel5.setText("Enter Amount:");

        sipm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sipm.setForeground(new java.awt.Color(255, 255, 255));
        sipm.setText("SIP:Monthly");
        sipm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sipmActionPerformed(evt);
            }
        });

        ls.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ls.setForeground(new java.awt.Color(255, 255, 255));
        ls.setText("LUMSUMP");
        ls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsActionPerformed(evt);
            }
        });

        piamt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(232, 236, 246));
        jLabel9.setText("Present Investment limit:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 236, 246));
        jLabel6.setText("Corpus generated as per present investment:");

        cgpi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cgpi.setForeground(new java.awt.Color(118, 255, 3));

        dur.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        res1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        res1.setForeground(new java.awt.Color(232, 236, 246));

        res2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        res2.setForeground(new java.awt.Color(118, 255, 3));

        jLayeredPane1.setBackground(new java.awt.Color(232, 236, 246));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(232, 236, 246))); // NOI18N
        jLayeredPane1.setForeground(new java.awt.Color(232, 236, 246));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(189, 195, 199));
        jLabel16.setText("6) Risk is inversely proportional to time period");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(189, 195, 199));
        jLabel17.setText("1) Higher the risk, higher the volatility");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(189, 195, 199));
        jLabel18.setText("2) Returns generated may deviate from results");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(189, 195, 199));
        jLabel19.setText("3) Returns may be negative at the time of global crisis");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(189, 195, 199));
        jLabel20.setText("4) Mutual funds are subject to market risk");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(189, 195, 199));
        jLabel21.setText("5) Doing your own research is advised before investing");

        jLayeredPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("GET FUNDS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtreqc, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sipm, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rcl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rcm, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(piamt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rch, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dur, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addComponent(jtage, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(38, 38, 38)
                                .addComponent(cgpi, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(res1)
                                .addGap(18, 18, 18)
                                .addComponent(res2)))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(jtreqc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sipm)
                            .addComponent(ls)
                            .addComponent(piamt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(dur))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rcl)
                            .addComponent(rcm)
                            .addComponent(rch))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtage, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cgpi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(res1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(res2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 1570, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rclActionPerformed
        if(rcl.isSelected())
        {
            rcm.setSelected(false);
            rch.setSelected(false);
        }
    }//GEN-LAST:event_rclActionPerformed

    private void rcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcmActionPerformed
        if(rcm.isSelected())
        {
            rcl.setSelected(false);
            rch.setSelected(false);
        }
    }//GEN-LAST:event_rcmActionPerformed

    private void rchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rchActionPerformed
        if(rch.isSelected())
        {
            rcm.setSelected(false);
            rcl.setSelected(false);
        }
    }//GEN-LAST:event_rchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jtreqc.setText("");
        jtage.setText("");
        dur.setText("");
        rcl.setSelected(false);
        rcm.setSelected(false);
        rch.setSelected(false);
        ls.setSelected(false);
        sipm.setSelected(false);
        piamt.setText("");
        res1.setText("");
        res2.setText("");
        cgpi.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sipmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sipmActionPerformed
        if(sipm.isSelected())
        {
            ls.setSelected(false);
        }
    }//GEN-LAST:event_sipmActionPerformed

    private void lsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsActionPerformed
        if(ls.isSelected())
        {
            sipm.setSelected(false);
        }
    }//GEN-LAST:event_lsActionPerformed

    static double getans(String str)
    {
        String ans="";
        for(int i=0;i<str.length()-7;i++)
        {
            ans=ans+str.charAt(i);
        }
        ans=ans+".";
        for(int i=str.length()-7;i<str.length();i++)
        {
            ans=ans+str.charAt(i);
        }
        double res;
        res=Double.parseDouble(ans);
        return res;
    }
    
    static String getdec(String str)
    {
        String ans="";
        for(int i=0;i<str.length();i++)
        {
            if(str.charAt(i)=='.')
            {
                break;
            }
            else
            {
                ans=ans+str.charAt(i);
            }
        }
        ans=ans+str.charAt(ans.length()+1)+".0";
        return ans;
        
    }
    
    static String getnum(String str)
    {
        String ans="";
        for(int i=0;i<str.length();i++)
        {
            if(str.charAt(i)=='.')
            {
                continue;
            }
            else
            {
                ans=ans+str.charAt(i);
            }
        }
        return ans;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if((jtreqc.getText().equals("")) || (piamt.getText().equals("")) || (!(sipm.isSelected()||ls.isSelected())) ||  (dur.getText().equals("")) || (!(rcl.isSelected()||rcm.isSelected() || rch.isSelected())) || (jtage.getText().equals("")))
        {
            JOptionPane.showMessageDialog(this, "Please fill all the details");
        }
        else
        {
            double amt=0;
            double getamt;
            double diff;
            double reqam;
            int c=0;
            String ans="";
            //int l=Integer.parseInt(piamt.getText())*(Integer.parseInt(dur.getText()));
            //String len=l+"";
            //l=len.length();
            if(piamt.getText().length()>7)
            {
                getamt=getans(piamt.getText());
                c++;
            }
            else
            {
                getamt=Double.parseDouble(piamt.getText());
            }


            if(ls.isSelected())
            {
                if(rcl.isSelected())
                {
                    if(c==0)
                    {
                        amt=getamt*(Math.pow(1.08, Double.parseDouble(dur.getText())))/10;
                        ans=getdec(amt+"");
                        diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(ans);
                        if(diff>0)
                        {
                            reqam=diff/(Math.pow(1.08, Double.parseDouble(dur.getText())));
                            res1.setText("You need to invest more amount to met your goal");
                            res2.setText("₹ "+Math.ceil(reqam)+"");
                        }
                        else
                        {
                            res1.setText("You don't need to invest more");
                            res2.setText("You would complete your goal with this investment!");
                        }

                    }
                    else
                    {
                        amt=getamt*(Math.pow(1.08, Double.parseDouble(dur.getText())));
                        ans=String.format("%.5f", amt);
                        diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(getnum(ans)+"00");
                        if(diff>0)
                        {
                            reqam=diff/(Math.pow(1.08, Double.parseDouble(dur.getText())));
                            res1.setText("You need to invest more amount to met your goal");
                            res2.setText("₹ "+Math.ceil(reqam)+"");
                        }
                        else
                        {
                            res1.setText("You don't need to invest more");
                            res2.setText("You would complete your goal with this investment!");
                        }
                    }

                }
                else if(rcm.isSelected())
                {
                    if(c==0)
                    {
                        amt=getamt*(Math.pow(1.11, Double.parseDouble(dur.getText())))/10;
                        ans=getdec(amt+"");
                        diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(ans);
                        if(diff>0)
                        {
                            reqam=diff/(Math.pow(1.11, Double.parseDouble(dur.getText())));
                            res1.setText("You need to invest more amount to met your goal");
                            res2.setText("₹ "+Math.ceil(reqam)+"");
                        }
                        else
                        {
                            res1.setText("You don't need to invest more");
                            res2.setText("You would complete your goal with this investment!");
                        }
                    }
                    else
                    {
                        amt=getamt*(Math.pow(1.11, Double.parseDouble(dur.getText())));
                        ans=String.format("%.5f", amt);
                        diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(getnum(ans)+"00");
                        if(diff>0)
                        {
                            reqam=diff/(Math.pow(1.11, Double.parseDouble(dur.getText())));
                            res1.setText("You need to invest more amount to met your goal");
                            res2.setText("₹ "+Math.ceil(reqam)+"");
                        }
                        else
                        {
                            res1.setText("You don't need to invest more");
                            res2.setText("You would complete your goal with this investment!");
                        }
                    }
                }
                else
                {
                    if(c==0)
                    {
                        amt=getamt*(Math.pow(1.15, Double.parseDouble(dur.getText())))/10;
                        ans=getdec(amt+"");
                        diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(ans);
                        if(diff>0)
                        {
                            reqam=diff/(Math.pow(1.15, Double.parseDouble(dur.getText())));
                            res1.setText("You need to invest more amount to met your goal");
                            res2.setText("₹ "+Math.ceil(reqam)+"");
                        }
                        else
                        {
                            res1.setText("You don't need to invest more");
                            res2.setText("You would complete your goal with this investment!");
                        }
                    }
                    else
                    {
                        amt=getamt*(Math.pow(1.15, Double.parseDouble(dur.getText())));
                        ans=String.format("%.5f", amt);;
                        diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(getnum(ans)+"00");
                        if(diff>0)
                        {
                            reqam=diff/(Math.pow(1.15, Double.parseDouble(dur.getText())));
                            res1.setText("You need to invest more amount to met your goal");
                            res2.setText("₹ "+Math.ceil(reqam)+"");
                        }
                        else
                        {
                            res1.setText("You don't need to invest more");
                            res2.setText("You would complete your goal with this investment!");
                        }
                    }
                }

            }
            if(sipm.isSelected())
            {
                double ml;
                double t=Double.parseDouble(dur.getText());

                if(rcl.isSelected())
                {
                    ml=(Math.pow(1.0066,(t*12) )-1)/0.0066;
                    amt=Math.ceil(ml*1.0066*getamt/10);
                    long r=(long)amt;
                    ans=r+"0.00";
                    diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(ans);
                    if(diff>0)
                    {
                        reqam=((diff)/(ml*1.0066));
                        res1.setText("You need to invest more amount to met your goal");
                        res2.setText("₹ "+Math.ceil(reqam)+"");
                    }
                    else
                    {
                        res1.setText("You don't need to invest more");
                        res2.setText("You would complete your goal with this investment!");
                    }
                }
                else if(rcm.isSelected())
                {
                    ml=(Math.pow(1.00916,(t*12) )-1)/0.00916;
                    amt=Math.ceil(ml*1.00916*getamt/10);
                    long r=(long)amt;
                    ans=r+"0.00";
                    diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(ans);
                    if(diff>0)
                    {
                        reqam=((diff)/(ml*1.00916));
                        res1.setText("You need to invest more amount to met your goal");
                        res2.setText("₹ "+Math.ceil(reqam)+"");
                    }
                    else
                    {
                        res1.setText("You don't need to invest more");
                        res2.setText("You would complete your goal with this investment!");
                    }

                }
                else
                {
                    ml=(Math.pow(1.0125,(t*12) )-1)/0.0125;
                    amt=Math.ceil(ml*1.0125*getamt/10);
                    long r=(long)amt;
                    ans=r+"0.00";
                    diff=Double.parseDouble(jtreqc.getText())-Double.parseDouble(ans);
                    if(diff>0)
                    {
                        reqam=((diff)/(ml*1.0125));
                        res1.setText("You need to invest more amount to met your goal");
                        res2.setText("₹ "+Math.ceil(reqam)+"");
                    }
                    else
                    {
                        res1.setText("You don't need to invest more");
                        res2.setText("You would complete your goal with this investment!");
                    }
                }
            }
            if(c>0)
            {
                c=0;
                cgpi.setText("₹ "+ans+" Cr.");
            }
            else
            {
                cgpi.setText("₹ "+ans);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        nw n=new nw();
        int dbtperc=0, equiperc=0, othrperc=0, age=Integer.parseInt(jtage.getText());
        if(Integer.parseInt(dur.getText())<8)
        {
            
                if(rcl.isSelected())
                {
                    if(Integer.parseInt(jtage.getText())<=45)
                    {
                        n.tf1.setText("Aditya Birla Sun Life Low Duration Fund");
                        n.tf1s.setText("Debt    Low Duration    5*");
                        n.tf2.setText("Edelweiss Banking and PSU Debt");
                        n.tf2s.setText("Debt    Banking and PSU    3*");
                        n.tf3.setText("Axis Bluechip Fund Direct Plan Growth");
                        n.tf3s.setText("Equity    Large Cap    5*");
                        n.tf4.setText("Kotak Gold Fund Direct Growth");
                        n.tf4s.setText("Others    Gold    4*");
                        n.tf5.setText("UTI Equity Fund Direct Growth");
                        n.tf5s.setText("Equity    Multi Cap    4*");
                        dbtperc=2*Integer.parseInt(jtage.getText());
                        n.debtperc.setText(dbtperc+"%");
                        equiperc=(int)((100-dbtperc)*0.6);
                        n.eqperc.setText(equiperc+"%");
                        othrperc=100-(dbtperc+equiperc);
                        n.otherperc.setText(othrperc+"%");
                        n.lcp.setText((0.6*equiperc)+"%");
                        n.lmcp.setText("0%");
                        n.mcp.setText("0%");
                        n.scp.setText("0%");
                        n.mulcp.setText((0.4*equiperc)+"%");
                        n.comp.setText(othrperc+"%");
                        n.fofp.setText("0%");
                        n.fetfp.setText("0%");
                        n.secp.setText("0%");
                        n.setVisible(true);
                    }
                    else
                    {
                        n.tf1.setText("Aditya Birla Sun Life Low Duration Fund");
                        n.tf1s.setText("Debt    Low Duration    5*");
                        n.tf2.setText("Edelweiss Banking and PSU Debt");
                        n.tf2s.setText("Debt    Banking and PSU    3*");
                        n.tf3.setText("DSP Government Securities Direct Plan Growth");
                        n.tf3s.setText("Debt    Gilt    5*");
                        n.tf4.setText("HDFC Short Term Debt Fund Direct Plan Growth");
                        n.tf4s.setText("Debt    Short Duration    4*");
                        n.tf5.setText("SBI Magnum Ultra Short Duration Fund Direct Growth");
                        n.tf5s.setText("Debt    Ultra-Short Duration    4*");
                        n.debtperc.setText("100%");
                        n.eqperc.setText("0%");
                        n.otherperc.setText("0%");
                        n.lcp.setText("0%");
                        n.lmcp.setText("0%");
                        n.mcp.setText("0%");
                        n.scp.setText("0%");
                        n.mulcp.setText("0%");
                        n.comp.setText("0%");
                        n.fofp.setText("0%");
                        n.fetfp.setText("0%");
                        n.secp.setText("0%");
                        n.setVisible(true);
                    }
                    
                }
                else if(rcm.isSelected())
                {
                    n.tf1.setText("HDFC Short Term Debt Fund - Direct Plan - Growth");
                    n.tf1s.setText("Debt    Low Duration    4*");
                    n.tf2.setText("PGIM India Diversified Equity Fund - Direct Plan - Growth");
                    n.tf2s.setText("Equity    Multicap    4*");
                    n.tf3.setText("Axis Bluechip Fund Direct Plan Growth");
                    n.tf3s.setText("Equity    Large Cap    5*");
                    n.tf4.setText("Axis Midcap Fund - Direct Plan - Growth");
                    n.tf4s.setText("Equity    Mid Cap    5*");
                    n.tf5.setText("Mirae Asset Emerging Bluechip Fund - Direct Plan - Growth");
                    n.tf5s.setText("Equity    Large & Mid Cap    5*");
                    dbtperc=Integer.parseInt(jtage.getText());
                    n.debtperc.setText(dbtperc+"%");
                    equiperc=100-dbtperc;
                    n.eqperc.setText(equiperc+"%");
                    othrperc=0;
                    n.otherperc.setText(othrperc+"%");
                    n.lcp.setText((0.4*equiperc)+"%");
                    n.lmcp.setText("0%");
                    n.mcp.setText((0.3*equiperc)+"%");
                    n.scp.setText("0%");
                    n.mulcp.setText((0.3*equiperc)+"%");
                    n.comp.setText("0%");
                    n.fofp.setText("0%");
                    n.fetfp.setText("0%");
                    n.secp.setText("0%");    
                    n.setVisible(true);
                }
                else
                {
                    n.tf1.setText("Axis Small Cap Fund Direct Growth");
                    n.tf1s.setText("Equity    Small Cap    4*");
                    n.tf2.setText("Canara Robeco Equity Diversified - Direct Plan - Growth");
                    n.tf2s.setText("Equity    Multicap    4*");
                    n.tf3.setText("Axis Bluechip Fund Direct Plan Growth");
                    n.tf3s.setText("Equity    Large Cap    5*");
                    n.tf4.setText("Axis Midcap Fund - Direct Plan - Growth");
                    n.tf4s.setText("Equity    Mid Cap    5*");
                    n.tf5.setText("Mirae Asset Emerging Bluechip Fund - Direct Plan - Growth");
                    n.tf5s.setText("Equity    Large & Mid Cap    5*");
                    dbtperc=0;
                    n.debtperc.setText(dbtperc+"%");
                    equiperc=100;
                    n.eqperc.setText(equiperc+"%");
                    othrperc=0;
                    n.otherperc.setText(othrperc+"%");
                    n.lcp.setText(age+"%");
                    n.lmcp.setText("0%");
                    n.mcp.setText((0.5*(equiperc-age))+"%");
                    n.scp.setText((0.3*(equiperc-age))+"%");
                    n.mulcp.setText((0.2*(equiperc-age))+"%");
                    n.comp.setText("0%");
                    n.fofp.setText("0%");
                    n.fetfp.setText("0%");
                    n.secp.setText("0%");
                    n.setVisible(true);
                }
        }
        else
        {
            if(rcl.isSelected())
                {
                    n.tf1.setText("Nippon India Small Cap Fund - Direct Plan - Growth");
                    n.tf1s.setText("Equity    Small Cap    4*");
                    n.tf2.setText("ICICI Prudential Bond Fund - Growth");
                    n.tf2s.setText("Debt    Medium to Long Duration    4*");
                    n.tf3.setText("Axis Bluechip Fund Direct Plan Growth");
                    n.tf3s.setText("Equity    Large Cap    5*");
                    n.tf4.setText("PGIM India Midcap Opportunities Fund - Direct Plan - Growth");
                    n.tf4s.setText("Equity    MidCap    5*");
                    n.tf5.setText("UTI Equity Fund Direct Growth");
                    n.tf5s.setText("Equity    Multi Cap    4*");
                    dbtperc=Integer.parseInt(jtage.getText());
                    n.debtperc.setText(dbtperc+"%");
                    equiperc=100-dbtperc;
                    n.eqperc.setText(equiperc+"%");
                    othrperc=0;
                    n.otherperc.setText(othrperc+"%");
                    n.lcp.setText((0.4*equiperc)+"%");
                    n.lmcp.setText("0%");
                    n.mcp.setText("0%");
                    n.scp.setText((0.3*equiperc)+"%");
                    n.mulcp.setText((0.3*equiperc)+"%");
                    n.comp.setText("0%");
                    n.fofp.setText("0%");
                    n.fetfp.setText("0%");
                    n.secp.setText("0%");
                    n.setVisible(true);
                    
                }
                else if(rcm.isSelected())
                {
                    n.tf1.setText("Franklin India Feeder - Franklin U.S. Opportunities Fund");
                    n.tf1s.setText("Fund of Funds    Others(Foreign)    2*");
                    n.tf2.setText("PGIM India Diversified Equity Fund - Direct Plan - Growth");
                    n.tf2s.setText("Equity    Multicap    4*");
                    n.tf3.setText("Nippon India Small Cap Fund - Direct Plan - Growth");
                    n.tf3s.setText("Equity    Small Cap    4*");
                    n.tf4.setText("Axis Midcap Fund - Direct Plan - Growth");
                    n.tf4s.setText("Equity    Mid Cap    5*");
                    n.tf5.setText("Mirae Asset Emerging Bluechip Fund - Direct Plan - Growth");
                    n.tf5s.setText("Equity    Large & Mid Cap    5*");
                    dbtperc=0;
                    n.debtperc.setText(dbtperc+"%");
                    equiperc=80;
                    n.eqperc.setText(equiperc+"%");
                    othrperc=20;
                    n.otherperc.setText(othrperc+"%");
                    n.lcp.setText("0%");
                    n.lmcp.setText((0.3*equiperc)+"%");
                    n.mcp.setText("0%");
                    n.scp.setText((0.3*equiperc)+"%");
                    n.mulcp.setText((0.2*equiperc)+"%");
                    n.comp.setText("0%");
                    n.fofp.setText("20%");
                    n.fetfp.setText("0%");
                    n.secp.setText("0%");
                    n.setVisible(true);
                }
                else
                {
                    n.tf1.setText("Mirae Asset Emerging Bluechip Fund - Direct Plan - Growth");
                    n.tf1s.setText("Equity    Large & Mid Cap    5*");
                    n.tf2.setText("Nippon India Pharma Fund - Direct Plan - Growth");
                    n.tf2s.setText("Equity    Others(Sectorial)    5*");
                    n.tf3.setText("Tata Digital India Fund - Direct Plan - Growth");
                    n.tf3s.setText("Equity    Others(Sectorial)    4*");
                    n.tf4.setText("Motilal Oswal Nasdaq 100 ETF");
                    n.tf4s.setText("ETFs    Others(Foreign equity)    4*");
                    n.tf5.setText("Nippon India Small Cap Fund - Direct Plan - Growth");
                    n.tf5s.setText("Equity    Small Cap    3*");
                    dbtperc=0;
                    n.debtperc.setText(dbtperc+"%");
                    equiperc=100;
                    n.eqperc.setText(equiperc+"%");
                    othrperc=100-equiperc;
                    n.otherperc.setText(othrperc+"%");
                    n.lcp.setText("0%");
                    n.lmcp.setText("20%");
                    n.mcp.setText("0%");
                    n.scp.setText("20%");
                    n.mulcp.setText("0%");
                    n.comp.setText("0%");
                    n.fofp.setText("0%");
                    n.fetfp.setText("40%");
                    n.secp.setText("20%");
                    n.setVisible(true);
                }
        }
        
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Page1 p=new Page1();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cgpi;
    public static javax.swing.JTextField dur;
    private javax.swing.JLabel hlin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField jtage;
    private javax.swing.JTextField jtreqc;
    private javax.swing.JRadioButton ls;
    private javax.swing.JTextField piamt;
    public transient javax.swing.JRadioButton rch;
    public static javax.swing.JRadioButton rcl;
    public static javax.swing.JRadioButton rcm;
    private javax.swing.JLabel res1;
    private javax.swing.JLabel res2;
    private javax.swing.JRadioButton sipm;
    // End of variables declaration//GEN-END:variables
}
