

import javax.swing.JFrame;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class Registration extends javax.swing.JFrame {

   File f=new File("C:\\Users\\Aayush\\Documents\\NetBeansProjects\\Login\\LogInData");
    
    public Registration() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    void createFolder()
    {
        if(!f.exists())
        {
            f.mkdirs();
        }
    }
    
     void createFile(String usn)
    {
        try {
            FileWriter fw=new FileWriter(f+"\\"+usn+".txt");
        } catch (IOException ex) {
            Logger.getLogger(GUILogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     void addData(String usn, String psd, String dob, String con, String eml)
     {
       try {
           RandomAccessFile raf=new RandomAccessFile(f+"\\"+usn+".txt","rw");
           raf.writeBytes(usn+"\r\n");
           raf.writeBytes(psd+"\r\n");
           raf.writeBytes(dob+"\r\n");
           raf.writeBytes(con+"\r\n");
           raf.writeBytes(eml+"\r\n");
       } catch (FileNotFoundException ex) {
           Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
       }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hlin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        regusr = new javax.swing.JTextField();
        regno = new javax.swing.JTextField();
        regdob = new javax.swing.JTextField();
        regmail = new javax.swing.JTextField();
        regpass = new javax.swing.JPasswordField();
        regsubmit = new javax.swing.JButton();
        regclr = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(232, 236, 246));
        jLabel3.setText("DOB:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(118, 255, 3));

        hlin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        hlin.setForeground(new java.awt.Color(46, 49, 50));
        hlin.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(hlin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1388, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hlin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1570, 60);

        jPanel2.setBackground(new java.awt.Color(46, 49, 50));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 236, 246));
        jLabel1.setText("Username:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(600, 200, 95, 33);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 236, 246));
        jLabel2.setText("DOB:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(600, 260, 95, 33);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 236, 246));
        jLabel4.setText("E-mail:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(600, 360, 95, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 236, 246));
        jLabel5.setText("Contact No.");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(600, 310, 100, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(232, 236, 246));
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(600, 400, 95, 36);

        regusr.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        regusr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regusrActionPerformed(evt);
            }
        });
        jPanel2.add(regusr);
        regusr.setBounds(760, 200, 170, 40);

        regno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(regno);
        regno.setBounds(760, 300, 170, 40);

        regdob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(regdob);
        regdob.setBounds(760, 250, 170, 40);

        regmail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(regmail);
        regmail.setBounds(760, 350, 170, 40);

        regpass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel2.add(regpass);
        regpass.setBounds(760, 400, 170, 40);

        regsubmit.setBackground(new java.awt.Color(118, 255, 3));
        regsubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regsubmit.setText("Submit");
        regsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regsubmitActionPerformed(evt);
            }
        });
        jPanel2.add(regsubmit);
        regsubmit.setBounds(640, 500, 95, 39);

        regclr.setBackground(new java.awt.Color(242, 38, 19));
        regclr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regclr.setText("Clear");
        regclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regclrActionPerformed(evt);
            }
        });
        jPanel2.add(regclr);
        regclr.setBounds(800, 500, 89, 39);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 60, 1570, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regusrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regusrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regusrActionPerformed

    private void regclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regclrActionPerformed
        regusr.setText("");
        regdob.setText("");
        regmail.setText("");
        regno.setText("");
        regpass.setText("");
    }//GEN-LAST:event_regclrActionPerformed

    private void regsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regsubmitActionPerformed
        if(regusr.getText().equals("") || regdob.getText().equals("") || regpass.getText().equals("") || regno.getText().equals("") || regmail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please fill all the details");
        }
        else
        {
            String un,db,ps,cn,em;
            un=regusr.getText().toString();
            db=regdob.getText().toString();
            ps=regpass.getText().toString();
            cn=regno.getText().toString();
            em=regmail.getText().toString();
            createFolder();
            createFile(un);
            addData(un,ps,db,cn,em);
            JOptionPane.showMessageDialog(this, "Successfully registered!");
            dispose();
            GUILogin l=new GUILogin();
            l.setVisible(true);
        }
    }//GEN-LAST:event_regsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hlin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton regclr;
    private javax.swing.JTextField regdob;
    private javax.swing.JTextField regmail;
    private javax.swing.JTextField regno;
    private javax.swing.JPasswordField regpass;
    private javax.swing.JButton regsubmit;
    private javax.swing.JTextField regusr;
    // End of variables declaration//GEN-END:variables
}
