
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class sipcalci extends javax.swing.JFrame {

    /**
     * Creates new form sipcalci
     */
    public sipcalci() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hlin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lreturns = new javax.swing.JLabel();
        lreturns1 = new javax.swing.JLabel();
        sdur = new javax.swing.JTextField();
        apm = new javax.swing.JTextField();
        lreturns2 = new javax.swing.JLabel();
        scv = new javax.swing.JTextField();
        lreturns3 = new javax.swing.JLabel();
        lreturns4 = new javax.swing.JLabel();
        lreturns5 = new javax.swing.JLabel();
        lreturns6 = new javax.swing.JLabel();
        lreturns7 = new javax.swing.JLabel();
        ocv = new javax.swing.JTextField();
        odur = new javax.swing.JTextField();
        oamt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        scal = new javax.swing.JButton();
        ocal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(118, 255, 3));

        hlin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        hlin.setForeground(new java.awt.Color(46, 49, 50));
        hlin.setText("Smart Finance Planner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(hlin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hlin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 520, 60);

        jPanel1.setBackground(new java.awt.Color(46, 49, 50));

        lreturns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lreturns.setForeground(new java.awt.Color(232, 236, 246));
        lreturns.setText("Amount per month");

        lreturns1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lreturns1.setForeground(new java.awt.Color(232, 236, 246));
        lreturns1.setText("Duration(1Y/3Y/5Y)");

        sdur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        apm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apmActionPerformed(evt);
            }
        });

        lreturns2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lreturns2.setForeground(new java.awt.Color(232, 236, 246));
        lreturns2.setText("Current value");

        scv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lreturns3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lreturns3.setForeground(new java.awt.Color(232, 236, 246));
        lreturns3.setText("SIP:");

        lreturns4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lreturns4.setForeground(new java.awt.Color(232, 236, 246));
        lreturns4.setText("ONE TIME:");

        lreturns5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lreturns5.setForeground(new java.awt.Color(232, 236, 246));
        lreturns5.setText("Amount ");

        lreturns6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lreturns6.setForeground(new java.awt.Color(232, 236, 246));
        lreturns6.setText("Duration(1Y/3Y/5Y)");

        lreturns7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lreturns7.setForeground(new java.awt.Color(232, 236, 246));
        lreturns7.setText("Current value");

        ocv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        odur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        oamt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(242, 38, 19));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        scal.setBackground(new java.awt.Color(0, 176, 255));
        scal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scal.setText("Calculate");
        scal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scalActionPerformed(evt);
            }
        });

        ocal.setBackground(new java.awt.Color(0, 176, 255));
        ocal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ocal.setText("Calculate");
        ocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lreturns3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lreturns6)
                                            .addComponent(lreturns5))
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(odur)
                                            .addComponent(oamt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lreturns4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lreturns2)
                                        .addGap(120, 120, 120)
                                        .addComponent(scv))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lreturns7)
                                        .addGap(120, 120, 120)
                                        .addComponent(ocv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lreturns1)
                                        .addComponent(lreturns))
                                    .addGap(71, 71, 71)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sdur, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(apm))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(scal)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ocal)
                        .addGap(136, 136, 136))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lreturns3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lreturns, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lreturns1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scal)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lreturns2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lreturns4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lreturns5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oamt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lreturns6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocal)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lreturns7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 520, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void apmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apmActionPerformed

    private void scalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scalActionPerformed
        int ampm,sdura;
        ampm=Integer.parseInt(apm.getText());
        sdura=Integer.parseInt(sdur.getText());
        double ret;
        if(sdura==1)
        {
            ret=ampm*12*(0.0396)+ampm*12;
            scv.setText(ret+"");
        }
        else if(sdura==3)
        {
            ret=ampm*36*(0.1395)+ampm*36;
            scv.setText(ret+"");
        }
        else if(sdura==5)
        {
            ret=ampm*60*(0.3439)+ampm*60;
            scv.setText(ret+"");
        }
        
    }//GEN-LAST:event_scalActionPerformed

    private void ocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocalActionPerformed
        int oamnt,odura;
        oamnt=Integer.parseInt(oamt.getText());
        odura=Integer.parseInt(odur.getText());
        double oret;
        if(odura==1)
        {
            oret=oamnt+oamnt*0.0698;
            ocv.setText(oret+"");
        }
        else if(odura==3)
        {
            oret=oamnt+oamnt*0.3617;
            ocv.setText(oret+"");
        }
        else
        {
            oret=oamnt+oamnt*0.6181;
            ocv.setText(oret+"");
        }
        
    }//GEN-LAST:event_ocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sipcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sipcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sipcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sipcalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sipcalci().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apm;
    private javax.swing.JLabel hlin;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lreturns;
    private javax.swing.JLabel lreturns1;
    private javax.swing.JLabel lreturns2;
    private javax.swing.JLabel lreturns3;
    private javax.swing.JLabel lreturns4;
    private javax.swing.JLabel lreturns5;
    private javax.swing.JLabel lreturns6;
    private javax.swing.JLabel lreturns7;
    private javax.swing.JTextField oamt;
    private javax.swing.JButton ocal;
    private javax.swing.JTextField ocv;
    private javax.swing.JTextField odur;
    private javax.swing.JButton scal;
    private javax.swing.JTextField scv;
    private javax.swing.JTextField sdur;
    // End of variables declaration//GEN-END:variables
}
