
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aayush
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        hlin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lgraph = new javax.swing.JLabel();
        lreturns = new javax.swing.JLabel();
        lyears = new javax.swing.JLabel();
        b1y = new javax.swing.JButton();
        b3y = new javax.swing.JButton();
        b5y = new javax.swing.JButton();
        ball = new javax.swing.JButton();
        b6m = new javax.swing.JButton();
        lyears1 = new javax.swing.JLabel();
        lyears2 = new javax.swing.JLabel();
        lyears3 = new javax.swing.JLabel();
        lyears4 = new javax.swing.JLabel();
        lyears5 = new javax.swing.JLabel();
        lyears6 = new javax.swing.JLabel();
        pcal = new javax.swing.JPanel();
        lyears7 = new javax.swing.JLabel();
        pret = new javax.swing.JPanel();
        lyears8 = new javax.swing.JLabel();
        ppc = new javax.swing.JPanel();
        lyears9 = new javax.swing.JLabel();
        phld = new javax.swing.JPanel();
        lyears10 = new javax.swing.JLabel();
        psd = new javax.swing.JPanel();
        lyears11 = new javax.swing.JLabel();
        pman = new javax.swing.JPanel();
        lyears13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(118, 255, 3));

        hlin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        hlin.setForeground(new java.awt.Color(46, 49, 50));
        hlin.setText("Smart Finance Planner");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(hlin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(940, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hlin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-30, 0, 1330, 60);

        jPanel1.setBackground(new java.awt.Color(46, 49, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(1270, 610));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 610));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 236, 246));
        jLabel1.setText("Axis Bluechip Fund Direct Plan Growth");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(189, 195, 199));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Equity");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(189, 195, 199));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Large Cap");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(189, 195, 199));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("5.0*");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199)));

        lreturns.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lreturns.setForeground(new java.awt.Color(232, 236, 246));

        lyears.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lyears.setForeground(new java.awt.Color(189, 195, 199));
        lyears.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        b1y.setBackground(new java.awt.Color(118, 255, 3));
        b1y.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b1y.setText("1Y");
        b1y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1yActionPerformed(evt);
            }
        });

        b3y.setBackground(new java.awt.Color(118, 255, 3));
        b3y.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b3y.setText("3Y");
        b3y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3yActionPerformed(evt);
            }
        });

        b5y.setBackground(new java.awt.Color(118, 255, 3));
        b5y.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b5y.setText("5Y");
        b5y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5yActionPerformed(evt);
            }
        });

        ball.setBackground(new java.awt.Color(118, 255, 3));
        ball.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ball.setText("ALL");
        ball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballActionPerformed(evt);
            }
        });

        b6m.setBackground(new java.awt.Color(118, 255, 3));
        b6m.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        b6m.setText("6M");
        b6m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6mActionPerformed(evt);
            }
        });

        lyears1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears1.setForeground(new java.awt.Color(189, 195, 199));
        lyears1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears1.setText("Rs. 33.09");

        lyears2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears2.setForeground(new java.awt.Color(189, 195, 199));
        lyears2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears2.setText("Rs. 14,552 Cr");

        lyears3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears3.setForeground(new java.awt.Color(189, 195, 199));
        lyears3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears3.setText("01 Jan 2013");

        lyears4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lyears4.setForeground(new java.awt.Color(189, 195, 199));
        lyears4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears4.setText("NAV-24-Jul-2020");

        lyears5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lyears5.setForeground(new java.awt.Color(189, 195, 199));
        lyears5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears5.setText("Fund Size");

        lyears6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lyears6.setForeground(new java.awt.Color(189, 195, 199));
        lyears6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears6.setText("Fund Started");

        pcal.setBackground(new java.awt.Color(97, 108, 111));
        pcal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pcalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pcalMouseExited(evt);
            }
        });

        lyears7.setBackground(new java.awt.Color(232, 236, 246));
        lyears7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears7.setForeground(new java.awt.Color(232, 236, 246));
        lyears7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears7.setText("SIP/ONE TIME CALCULATOR");

        javax.swing.GroupLayout pcalLayout = new javax.swing.GroupLayout(pcal);
        pcal.setLayout(pcalLayout);
        pcalLayout.setHorizontalGroup(
            pcalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lyears7)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pcalLayout.setVerticalGroup(
            pcalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pcalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lyears7)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pret.setBackground(new java.awt.Color(97, 108, 111));
        pret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pretMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pretMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pretMouseExited(evt);
            }
        });

        lyears8.setBackground(new java.awt.Color(232, 236, 246));
        lyears8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears8.setForeground(new java.awt.Color(232, 236, 246));
        lyears8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears8.setText("RETURNS");

        javax.swing.GroupLayout pretLayout = new javax.swing.GroupLayout(pret);
        pret.setLayout(pretLayout);
        pretLayout.setHorizontalGroup(
            pretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pretLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lyears8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pretLayout.setVerticalGroup(
            pretLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pretLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lyears8)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        ppc.setBackground(new java.awt.Color(97, 108, 111));
        ppc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppcMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppcMouseExited(evt);
            }
        });

        lyears9.setBackground(new java.awt.Color(232, 236, 246));
        lyears9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears9.setForeground(new java.awt.Color(232, 236, 246));
        lyears9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears9.setText("PROS/CONS");

        javax.swing.GroupLayout ppcLayout = new javax.swing.GroupLayout(ppc);
        ppc.setLayout(ppcLayout);
        ppcLayout.setHorizontalGroup(
            ppcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lyears9)
                .addGap(89, 89, 89))
        );
        ppcLayout.setVerticalGroup(
            ppcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppcLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lyears9)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        phld.setBackground(new java.awt.Color(97, 108, 111));
        phld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phldMouseExited(evt);
            }
        });

        lyears10.setBackground(new java.awt.Color(232, 236, 246));
        lyears10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears10.setForeground(new java.awt.Color(232, 236, 246));
        lyears10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears10.setText("HOLDING ANALYSIS");

        javax.swing.GroupLayout phldLayout = new javax.swing.GroupLayout(phld);
        phld.setLayout(phldLayout);
        phldLayout.setHorizontalGroup(
            phldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, phldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lyears10)
                .addGap(50, 50, 50))
        );
        phldLayout.setVerticalGroup(
            phldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phldLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lyears10)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        psd.setBackground(new java.awt.Color(97, 108, 111));
        psd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psdMouseExited(evt);
            }
        });

        lyears11.setBackground(new java.awt.Color(232, 236, 246));
        lyears11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears11.setForeground(new java.awt.Color(232, 236, 246));
        lyears11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears11.setText("SCHEME DETAILS");

        javax.swing.GroupLayout psdLayout = new javax.swing.GroupLayout(psd);
        psd.setLayout(psdLayout);
        psdLayout.setHorizontalGroup(
            psdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, psdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lyears11)
                .addGap(59, 59, 59))
        );
        psdLayout.setVerticalGroup(
            psdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(psdLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lyears11)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pman.setBackground(new java.awt.Color(97, 108, 111));
        pman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmanMouseExited(evt);
            }
        });

        lyears13.setBackground(new java.awt.Color(232, 236, 246));
        lyears13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lyears13.setForeground(new java.awt.Color(232, 236, 246));
        lyears13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lyears13.setText("FUND MANAGER");

        javax.swing.GroupLayout pmanLayout = new javax.swing.GroupLayout(pman);
        pman.setLayout(pmanLayout);
        pmanLayout.setHorizontalGroup(
            pmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pmanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lyears13)
                .addGap(60, 60, 60))
        );
        pmanLayout.setVerticalGroup(
            pmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pmanLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lyears13)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(242, 38, 19));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(340, 340, 340)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lyears)
                                    .addComponent(lreturns)))
                            .addComponent(lgraph, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(b6m, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b1y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b3y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b5y, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ball))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(lyears4)
                                .addGap(126, 126, 126)
                                .addComponent(lyears5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(lyears1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(lyears2)))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lyears6))
                            .addComponent(lyears3))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ppc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pret, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pcal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(psd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lreturns, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lyears))
                        .addGap(14, 14, 14)
                        .addComponent(lgraph, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b1y, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3y, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5y, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ball, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6m, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lyears1)
                            .addComponent(lyears2)
                            .addComponent(lyears3)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lyears4)
                            .addComponent(lyears5)
                            .addComponent(lyears6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ppc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(359, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 1300, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pmanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmanMouseExited
        Color c=new Color(90,108,111);
        pman.setBackground(c);
    }//GEN-LAST:event_pmanMouseExited

    private void pmanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmanMouseEntered
        Color c=new Color(71,83,94);
        pman.setBackground(c);
    }//GEN-LAST:event_pmanMouseEntered

    private void psdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdMouseExited
        Color c=new Color(90,108,111);
        psd.setBackground(c);
    }//GEN-LAST:event_psdMouseExited

    private void psdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdMouseEntered
        Color c=new Color(71,83,94);
        psd.setBackground(c);
    }//GEN-LAST:event_psdMouseEntered

    private void phldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phldMouseExited
        Color c=new Color(90,108,111);
        phld.setBackground(c);
    }//GEN-LAST:event_phldMouseExited

    private void phldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phldMouseEntered
        Color c=new Color(71,83,94);
        phld.setBackground(c);
    }//GEN-LAST:event_phldMouseEntered

    private void phldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phldMouseClicked
        axismfholdings hl=new axismfholdings();
        hl.setVisible(true);
    }//GEN-LAST:event_phldMouseClicked

    private void ppcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppcMouseExited
        Color c=new Color(90,108,111);
        ppc.setBackground(c);
    }//GEN-LAST:event_ppcMouseExited

    private void ppcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppcMouseEntered
        Color c=new Color(71,83,94);
        ppc.setBackground(c);
    }//GEN-LAST:event_ppcMouseEntered

    private void ppcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppcMouseClicked
        axismfpc pc=new axismfpc();
        pc.setVisible(true);
    }//GEN-LAST:event_ppcMouseClicked

    private void pretMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretMouseExited
        Color c=new Color(90,108,111);
        pret.setBackground(c);
    }//GEN-LAST:event_pretMouseExited

    private void pretMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretMouseEntered
        Color c=new Color(71,83,94);
        pret.setBackground(c);
    }//GEN-LAST:event_pretMouseEntered

    private void pretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pretMouseClicked
        axismfreturns a=new axismfreturns();
        a.setVisible(true);
    }//GEN-LAST:event_pretMouseClicked

    private void pcalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcalMouseExited
        Color c=new Color(90,108,111);
        pcal.setBackground(c);
    }//GEN-LAST:event_pcalMouseExited

    private void pcalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcalMouseEntered
        Color c=new Color(71,83,94);
        pcal.setBackground(c);
    }//GEN-LAST:event_pcalMouseEntered

    private void pcalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcalMouseClicked
        sipcalci s=new sipcalci();
        s.setVisible(true);
    }//GEN-LAST:event_pcalMouseClicked

    private void b6mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6mActionPerformed
        lgraph.setIcon(new ImageIcon("C:\\Users\\Aayush\\Documents\\NetBeansProjects\\Login\\axis6m.png"));
        lreturns.setText("-5.89%");
        lyears.setText("6M Returns");
    }//GEN-LAST:event_b6mActionPerformed

    private void ballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballActionPerformed
        lgraph.setIcon(new ImageIcon("C:\\Users\\Aayush\\Documents\\NetBeansProjects\\Login\\axisall.png"));
        lreturns.setText("14.01%");
        lyears.setText("All Returns");
    }//GEN-LAST:event_ballActionPerformed

    private void b5yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5yActionPerformed
        lgraph.setIcon(new ImageIcon("C:\\Users\\Aayush\\Documents\\NetBeansProjects\\Login\\axis5y.png"));
        lreturns.setText("10.01%");
        lyears.setText("5Y Returns");
    }//GEN-LAST:event_b5yActionPerformed

    private void b3yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3yActionPerformed
        lgraph.setIcon(new ImageIcon("C:\\Users\\Aayush\\Documents\\NetBeansProjects\\Login\\axis2y.png"));
        lreturns.setText("10.84%");
        lyears.setText("3Y Returns");
    }//GEN-LAST:event_b3yActionPerformed

    private void b1yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1yActionPerformed
        lgraph.setIcon(new ImageIcon("C:\\Users\\Aayush\\Documents\\NetBeansProjects\\Login\\axis1y.png"));
        lreturns.setText("6.98%");
        lyears.setText("1Y Returns");
    }//GEN-LAST:event_b1yActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void psdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdMouseClicked
        axismfschemedet obj=new axismfschemedet();
        obj.setVisible(true);
    }//GEN-LAST:event_psdMouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1y;
    private javax.swing.JButton b3y;
    private javax.swing.JButton b5y;
    private javax.swing.JButton b6m;
    private javax.swing.JButton ball;
    private javax.swing.JLabel hlin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lgraph;
    private javax.swing.JLabel lreturns;
    private javax.swing.JLabel lyears;
    private javax.swing.JLabel lyears1;
    private javax.swing.JLabel lyears10;
    private javax.swing.JLabel lyears11;
    private javax.swing.JLabel lyears13;
    private javax.swing.JLabel lyears2;
    private javax.swing.JLabel lyears3;
    private javax.swing.JLabel lyears4;
    private javax.swing.JLabel lyears5;
    private javax.swing.JLabel lyears6;
    private javax.swing.JLabel lyears7;
    private javax.swing.JLabel lyears8;
    private javax.swing.JLabel lyears9;
    private javax.swing.JPanel pcal;
    private javax.swing.JPanel phld;
    private javax.swing.JPanel pman;
    private javax.swing.JPanel ppc;
    private javax.swing.JPanel pret;
    private javax.swing.JPanel psd;
    // End of variables declaration//GEN-END:variables
}
